- name: Install dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: Create Docker systemd service override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Configure Docker daemon for secure operation
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
    mode: '0644'

- name: Reload systemd and restart Docker
  shell: |
    systemctl daemon-reexec
    systemctl daemon-reload
    systemctl restart docker
  register: docker_restart
  failed_when: docker_restart.rc != 0
  ignore_errors: true

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Create Docker volume for registry
  community.docker.docker_volume:
    name: registry_data
    state: present

- name: Run local Docker registry
  community.docker.docker_container:
    name: local-registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
      - "{{ registry_host.port }}:{{ services.registry }}"
    volumes:
      - registry_data:/var/lib/registry


