---
- name: Install ingress-nginx controller
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.2/deploy/static/provider/cloud/deploy.yaml
  args:
    creates: /tmp/ingress-nginx-applied

- name: Mark ingress-nginx as applied
  file:
    path: /tmp/ingress-nginx-applied
    state: touch

- name: Wait for ingress-nginx controller to be ready
  shell: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=300s
  retries: 3
  delay: 10

- name: Create registry ingress with CORS support
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: registry-ingress
        namespace: default
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "http://{{ registry_host.ip }}:{{ registry_host.ui_port }}"
          nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, HEAD"
          nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Docker-Content-Digest"
          nginx.ingress.kubernetes.io/cors-expose-headers: "Docker-Content-Digest,Docker-Distribution-Api-Version,Location"
          nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
          nginx.ingress.kubernetes.io/cors-max-age: "1728000"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      spec:
        rules:
        - host: registry.local
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: registry-service
                  port:
                    number: 5000
    state: present
  when: registry_host is defined

- name: Create registry service for ingress
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: registry-service
        namespace: default
      spec:
        selector:
          app: registry
        ports:
        - port: 5000
          targetPort: 5000
          protocol: TCP
        type: ClusterIP
    state: present
  when: registry_host is defined
