- name: Ensure /etc/rancher/k3s directory exists
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Configure containerd to trust the local registry
  copy:
    dest: /etc/rancher/k3s/registries.yaml
    content: |
      mirrors:
        "{{ registry_host.ip }}:{{ registry_host.port }}":
          endpoint:
            - "http://{{ registry_host.ip }}:{{ registry_host.port }}"
    mode: '0644'
  notify: Reboot node if registry config changed
