- hosts: master
  become: yes
  vars:
    k3s_token: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
  roles:
    - k3s_master
    - metallb
    - ingress_nginx
    - security

- hosts: workers
  become: yes
  vars:
    k3s_token: "{{ hostvars[master_node.hostname].k3s_token }}"
  roles:
    - k3s_worker
